---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# actsims

<!-- badges: start -->
<!-- badges: end -->

The goal of actsims is to ...

## Installation

You can install the development version of actsims like so:

``` r
# install.packages("devtools")
devtools::install_github("acastroaraujo/actsims")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example, message=FALSE}
library(tidyverse)
library(actsims)


## create an InteRact class
act <- interact(dictionary = "usfullsurveyor2015", equations = "us2010")
act # custom print

# calculate deflection for specific ABOs in dictionary
act$deflection(list(A = "deadbeat", B = "kill", O = "god"))
act$deflection(list(A = "deadbeat", B = "kill", O = "deadbeat"))

# create a grid of specific AB0s
events <- tidyr::crossing(
  A = act$dictionary |> dplyr::filter(component == "identity") |> dplyr::pull(term),
  B = act$dictionary |> dplyr::filter(component == "behavior") |> dplyr::pull(term) |> sample(3),
  O = act$dictionary |> dplyr::filter(component == "identity") |> dplyr::pull(term)
) 


# calculate deflection for grid
events$d <- act$deflection(events)

str(events)

# act$optimal_behavior()
# act$reidentify_actor()
# act$reidentify_object()
# act$nearest_neighbors()
# act$transient_impressions()

```


